# https://github.com/be5invis/Iosevka/blob/master/doc/custom-build.md

[buildPlans.McIosevka]
family = "McIosevka"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.McIosevka.variants.design]

# ABCDEFGHIJKLMNOPQRSTUVWXYZ
capital-a = "straight-serifless"
capital-b = "standard-interrupted-serifless"
capital-c = "bilateral-inward-serifed"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-inward-serifed-hooked"
capital-h = "serifless"                
capital-i = "short-serifed"
capital-j = "serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging"
capital-n = "standard"
# capital-o = no options (yet)
capital-p = "open"
capital-q = "crossing"
capital-r = "curly-open"
capital-s = "bilateral-inward-serifed"
capital-t = "serifless"
capital-u = "toothless-corner"
capital-v = "straight"
capital-w = "straight"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifed"

# abcdefghijklmnopqrstuvwxyz

# a = "double-storey-toothless-corner"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
c = "bilateral-inward-serifed"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "double-storey-open"
h = "straight"
i = "zshaped"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "zshaped"
m = "earless-corner-double-arch-short-leg"
n = "earless-corner-straight"
# o = no options (yet)
p = "earless-corner"
q = "earless-corner"
r = "earless-corner"
s = "bilateral-inward-serifed"
t = "flat-hook"
u = "toothless-corner"
v = "straight"
w = "straight"   
x = "curly-serifless"
y = "curly-turn"
z = "curly-serifed"

# 0123456789
zero = "reverse-slashed-split"
one = "no-base"
two = "straight-neck"   
three = "flat-top"
four = "open-non-crossing"
five = "oblique-upper-left-bar"
six = "straight-bar"   
seven = "bend-serifless" 
eight = "two-circles"
nine = "straight-bar"

# ~*_¶^(){}#&@$¢%|

tilde = "low"  
asterisk = "hex-low"
underscore = "low"  
pilcrow = "high"
caret = "medium"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "upright"
ampersand = "closed"
at = "fourfold-solid-inner"    
dollar = "interrupted"
cent = "through"  
percent = "rings-segmented-slash"
bar = "force-upright"

lig-ltgteq = "slanted" # <= & >= 
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "corner" # ?
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.McIosevka.ligations] 
enables = [
    "center-ops",               # Vertically align some of the operators (like *) to the center position it is before or after a "center" operator (like +).
    "arrow",                    # Enable ligation set that forms arrows.
    "arrow2",                   # Enable ligation for more arrows, like >>=.
    "trig",                     # Enable ligation for <|, |> , <||, and other bar-and-angle-bracket symbols.
    "ineq",                     # Enable ligation for <= and >=
    "exeq",                     # Enable ligation for != and !==
    "ltgt-diamond",             # Enable ligation for <> as diamond.
    "brst",                     # Center asterisk in (* and *)
    "kern-dotty",               # Move connecting dotty punctuations closer, like for ::, ::: and ...
    "kern-bars",                # Move consecutive bars closer, like for ||, ||| and //
    "llggeq",                   # Enable ligation for <<=, >>= as shift operator
    "dot-as-operator",          # Treat dot (.) as operator and perform chained centering
    "html-comment",             # Enable ligation for <!-- and <!---
    "brace-bar",                # Enable ligation for {| and |}
    "brack-bar",                # Enable ligation for [| and |]
    "connected-number-sign",    # Make contiguous number signs (like ##) connected
    "connected-tilde-as-wave"   # Make contiguous ASCII tildes (like ~~) connected as a wave line
]

[buildPlans.McIosevka.widths.normal]
shape = 475
menu = 5
css = "normal"

[buildPlans.McIosevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.McIosevka.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.McIosevka.weights.thin]
shape = 200
menu = 200
css = 200

[buildPlans.McIosevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.McIosevka.weights.bold]
shape = 700
menu = 700
css = 700