[buildPlans.McIosevka]
family = "McIosevka"
spacing = "fontconfig-mono"
serifs = "sans"
no-cv-ss = false

[buildPlans.McIosevka.variants]
inherits = "ss20"

[buildPlans.McIosevka.variants.design]
capital-g = "toothless-corner-inward-serifed-capped"
capital-i = "short-serifed"
capital-n = "standard"
capital-q = "crossing"
a = "double-storey"
b = "toothless-corner"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "double-storey-open"
h = "straight"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
l = "serifed-diagonal-tailed"
m = "earless-rounded-double-arch-short-leg"
n = "earless-rounded-straight"
p = "earless-rounded"
q = "earless-rounded-diagonal-tailed"
r = "earless-corner"
t = "diagonal-tailed-short-neck"
u = "toothless-corner"
v = "curly"
y = "cursive-flat-hook"
zero = "slashed"
two = "straight-neck"
three = "flattop"
four = "open-non-crossing"
five = "oblique-upper-left-bar"
six = "straight-bar"
seven = "curly-serifless"
eight = "two-circles"
nine = "straight-bar"
asterisk = "penta-low"
underscore = "above-baseline"
caret = "medium"
paren = "flat-arc"
number-sign = "upright"
ampersand = "closed"
at = "threefold"
dollar = "interrupted-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
lig-ltgteq = "slanted"
question = "corner-flat-hooked"

[buildPlans.McIosevka.ligations]
enables = [
    "center-ops",               # Vertically align some of the operators (like *) to the center position it is before or after a "center" operator (like +).
    "arrow",                    # Enable ligation set that forms arrows.
    "trig",                     # Enable ligation for <|, |> , <||, and other bar-and-angle-bracket symbols.
    "ineq",                     # Enable ligation for <= and >=
    "exeq",                     # Enable ligation for != and !==
    "ltgt-diamond",             # Enable ligation for <> as diamond.
    "brst",                     # Center asterisk in (* and *)
    "kern-dotty",               # Move connecting dotty punctuations closer, like for ::, ::: and ...
    "html-comment",             # Enable ligation for <!-- and <!---
    "brace-bar",                # Enable ligation for {| and |}
    "brack-bar",                # Enable ligation for [| and |]
    "connected-number-sign",    # Make contiguous number signs (like ##) connected
    "connected-tilde-as-wave"   # Make contiguous ASCII tildes (like ~~) connected as a wave line
]

# [buildPlans.McIosevka.widths.condensed]
# shape = 434
# menu = 3
# css = "condensed"

[buildPlans.McIosevka.widths.normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.McIosevka.weights.thin]
shape = 100
menu  = 100
css   = 100

[buildPlans.McIosevka.weights.light]
shape = 250
menu  = 300
css   = 250

[buildPlans.McIosevka.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.McIosevka.weights.medium]
shape = 550
menu  = 500
css   = 550

[buildPlans.McIosevka.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.McIosevka.weights.heavy]
shape = 850
menu  = 900
css   = 850